In [1]:
import numpy as np
import pandas as pd

![Split-apply-combine paradigm for a reduction](../Images/Split-apply-combine_paradigm_for_a_reduction.png)

> **Split-apply-combine paradigm for a reduction**

![Split-apply-combine paradigm for a transformation](../Images/Split-apply-combine_paradigm_for_a_transformation.png)

> **Split-apply-combine paradigm for a transformation**

# **Group by basics**

In [2]:
df = pd.DataFrame([
    ["group_a", 0],
    ["group_a", 2],
    ["group_b", 1],
    ["group_b", 3],
    ["group_b", 5],
], columns=["group", "value"]).convert_dtypes(dtype_backend="numpy_nullable")

df

     group  value
0  group_a      0
1  group_a      2
2  group_b      1
3  group_b      3
4  group_b      5

In [4]:
df.groupby(by="group").sum()

         value
group
group_a      2
group_b      9

In [5]:
df.groupby("group").agg("sum")

         value
group
group_a      2
group_b      9

In [6]:
df.groupby("group").transform("sum")

   value
0      2
1      2
2      9
3      9
4      9

In [7]:
df[["value"]].div(df.groupby("group").transform("sum"))

      value
0       0.0
1       1.0
2  0.111111
3  0.333333
4  0.555556

In [8]:
df

     group  value
0  group_a      0
1  group_a      2
2  group_b      1
3  group_b      3
4  group_b      5

In [9]:
df.groupby("group", as_index=False).agg("sum")

     group  value
0  group_a      2
1  group_b      9

In [10]:
df.groupby("group").min()

         value
group
group_a      0
group_b      1

In [13]:
df.groupby("group").agg(sum_of_value=pd.NamedAgg(column="value", aggfunc="sum"))

         sum_of_value
group
group_a             2
group_b             9

# **Grouping and calculating multiple columns**